cd /sys/devices/system/cpu/cpu0/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu1/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu2/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu3/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu4/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu5/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu6/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
cd /sys/devices/system/cpu/cpu7/cpufreq/
echo performance>scaling_governor
cat scaling_governor 
cat scaling_cur_freq
