from src.algorithm import *
import warnings

if __name__ == "__main__":
    warnings.simplefilter("error")
    di = DI4SelfAdaptive()
    t1_profile = DIProfile(10, 200)
    t2_profile = DIProfile(300, 20)
    t3_profile = DIProfile(30, 400)
    t4_profile = DIProfile(500, 40)
    t1 = Task("t1")
    t2 = Task("t2")
    t3 = Task("t3")
    t4 = Task("t4")
    t1.loadProfile(t1_profile)
    t2.loadProfile(t2_profile)
    t3.loadProfile(t3_profile)
    t4.loadProfile(t4_profile)
    di.addTask(t1)
    di.addTask(t2)
    di.addTask(t3)
    di.addTask(t4)
    di.solve(2)
    di.solve(3)
    di.solve(1)
    di.importTask("bzip2")
    di.solve(1)
    di.clean()
    di.solve(2)
